### ISSUE TITLE
Question about simplify the graph

### ISSUE THREAD

**Issue by ETC100** [ComparativeGenomicsToolkit/cactus#1077]
Hello, I have used cactus v2.6.0 pangenome function to generate a graph pan-genome directly. However, the graph was too large containing too many SNPs and short INDELs, which may make vg call function hard to complete the SV calling (10x depth data can't called for 2 days). Can I filter the SNP and short INDELs out from the output VCF and use vg construct to regenerate a smaller graph? If I did this, is there any severe influence on the quality of the graph? Or there may some other method for cactus to generate a smaller graph?

**Comment by glennhickey** [comment]
You might consider trying PanGenie instead -- it should be much less affected by graph complexity (and requires no mapping).  

Otherwise, you can simplify the graph using the the "--filter" option. By default it's set to 2, but you can crank that up to require higher frequency in your graph variants.

In vg we are working on a way to quickly produce a sample graph from the full graph using kmers from a set of reads.  It should be ready soon, and is what we hope will address the general problem of graphs getting too complex going forward.
