### ISSUE TITLE
Problem with reproducing Cactus-pangenome example

### ISSUE THREAD

**Issue by BlackSlipper** [ComparativeGenomicsToolkit/cactus#1078]
Hello, i have been having some troubles replicating the results from https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/doc/mc-pangenomes/README.md. To be specific, i could not split the genomes into 28+ chromosomes. 

I am currently working on the chicken data. I have tried the latest cactus-pangenome version and the downgraded version when the chicken seqfile(10-chicken-pg-2022-09-23-seqfile.txt) was made, but could not reproduce the results. 

i have used the same seqfile and the commands( except for AWS-specific options like --batchSystem, --defaultPreemptable, --nodeType, --nodeStorage, --maxNodes, --betaInertia, --targetTime and --provisioner) 

These are the commands i tried using:
```shell
export MYBUCKET=/cactus_wd/
export MYJOBSTORE=/cactus_wd/jobstore
export VERSION=june28

cactus-minigraph ${MYJOBSTORE} seqfile ${MYBUCKET}/chicken-pg-${VERSION}.gfa.gz --reference galGal6 --logFile chicken-pg-${VERSION}-minigraph.log --maxCores 128

cactus-graphmap ${MYJOBSTORE} seqfile ${MYBUCKET}/chicken-pg-${VERSION}.gfa.gz ${MYBUCKET}/chicken-pg-${VERSION}.paf  --outputFasta ${MYBUCKET}/chicken-pg-${VERSION}.gfa.fa.gz --reference galGal6 --mapCores 16 --logFile ${MYBUCKET}/chicken-pg-${VERSION}-graphmap.log --mapCores 16 --maxCores 128

cactus-graphmap-split ${MYJOBSTORE} seqfile ${MYBUCKET}/chicken-pg-${VERSION}.gfa.gz ${MYBUCKET}/chicken-pg-${VERSION}.paf --outDir ${MYBUCKET}/chroms-chicken-pg-${VERSION} --otherContig chrOther --refContigs $(for i in `seq 33`; do echo chr$i; done ; echo "chrW chrZ") --reference galGal6  --logFile ${MYBUCKET}/chicken-pg-${VERSION}-split.log --maxCores 128

``` 

However the results were like this:

```shell
root@0fb9fccc36e8:/cactus_wd# ls
chicken-pg-june28-graphmap.log   chicken-pg-june28.gaf.gz     chicken-pg-june28.paf                chroms-chicken-pg-june28
chicken-pg-june28-minigraph.log  chicken-pg-june28.gfa.fa.gz  chicken-pg-june28.paf.filter.log     seqfile
chicken-pg-june28-split.log      chicken-pg-june28.gfa.gz     chicken-pg-june28.paf.unfiltered.gz

root@0fb9fccc36e8:/cactus_wd/chroms-chicken-pg-june28# ls
_AMBIGUOUS_  chr10  chr12  chr3  chr5  chr7  chr9      chrZ           contig_sizes.tsv     seqfiles
chr1         chr11  chr2   chr4  chr6  chr8  chrOther  chromfile.txt  minigraph.split.log


``` 

(I was supposed to have chr1~chr33, chrW, chrZ, chrOther i think...)
I could only get results of chr1~ chr12, chrZ, chrOther :( 
Even though i followed the commands, I was not able to split the assemblies into chromosomes fully. Would there be a reason to this roblem? How would i be able to fix this?

**Comment by glennhickey** [comment]
A few things:
* regardless of the decomposition, you will get all the chromosomes in your final output (ie the .gfa / .gbz etc).  It's just that the smaller chromosomes all get lumped into `chrOther` in the decomposition.
* In v2.6.0, cactus used the chromosome sizes to make this determination, which does indeed result in all but 13 chromosomes going into `chrOther`.
* In v2.6.1, this logic is changed to use a [regex](https://github.com/ComparativeGenomicsToolkit/cactus/blob/ceed5819d23f150dc507c817fa9a84323691037f/src/cactus/cactus_progressive_config.xml#L368) because the size heuristic doesn't work well in cases like chicken, and for the new visualization options it's important to get chromosome graphs.
* I just added a new example to https://github.com/ComparativeGenomicsToolkit/cactus/tree/master/doc/mc-pangenomes#readme for the chicken data with v2.6.1

All that said, `--refContigs` is supposed to override all the automatic determinations I described above.  In your case, this does not seem to be happening, which would be a bug.  I will check to see if it's an issue in the latest release and fix it if it is.  Thanks for raising this issue.
