### ISSUE TITLE
Aligning maf to positive chain

### ISSUE THREAD

**Issue by Alchimic007** [ComparativeGenomicsToolkit/cactus#1219]
Hello,

Sorry to bother. Just wanted to ask how to allign maf file, extracted from hal file (with referencing specific  genome and chromosome) to positive chain to get then axt file with maftoaxt program from UCSC toolkit?  I used hal to maf command from HALtoolkit to allign cow (bos taurus) genome against separate human chromosomes as reference: #hal2maf /users/hpctestuser/241-mammalian-2020v2.hal /users/hpctestuser/mprylutskyi/HALtools/DESCHRAMBLER_alignment/cow/bosTau_chr1.maf --refGenome Homo_sapiens --refSequence chr1 --targetGenomes Bos_taurus. Then when I was running mafToAxt:  mafToAxt /users/hpctestuser/mprylutskyi/HALtools/DESCHRAMBLER_alignment/cow/bosTau_chr1.maf Homo_sapiens Bos_taurus /users/hpctestuser/mprylutskyi/HALtools/DESCHRAMBLER_alignment/cow/bosTau_chr1.axt 
an error occured:   Target sequence not on positive strand. Is there any way to solve this issue, maybe there is an option to allign strictly to positive strand. The case is I need separate mafs and then axts and chains for each reference chromosome. I would be very appreciated for any info and help

**Comment by glennhickey** [comment]
`hal2maf` should guarantee your first row (`Homo_sapiens` in this case) is on the positive strand.  But there can be later rows also on `Homo_sapiens` due to paralogy that are on the negative strand, and this is what `mafToAxt` is complaining about.  You can strip these out with `mafDuplicateFilter -k` and it should work.  

I'd recommend using `cactus-hal2maf --dupeMode single` to make you maf in this case.

**Comment by Alchimic007** [comment]
Thank you.  Can I use cactus-hal2maf separately somehow or only within cactus package, I mean should I install cactus to work with this command or HALtoolkit alone is enough. Thank you
