### ISSUE TITLE
Trying to run cactus-hal2maf with --refGenome Anc0

### ISSUE THREAD

**Issue by BlackSlipper** [ComparativeGenomicsToolkit/cactus#1331]
Hi, I created a pangenome and got a HAL file. 

i am trying to convert HAL file into MAF conserving all the non-reference alignments.

In this context, is it okay to use "**cactus-hal2maf with --refGenome Anc0**" option? 

It says in the document that it is recommended to create the maf using the --noAncestors options with cactus-hal2maf.

What are the pros and cons of setting --refGenome Anc0 ?

**Comment by glennhickey** [comment]
most people don't want the ancestors in the maf, so that's why the `--noAncestors` is recommended.  If you want non-reference sequence, `--refGenome Anc0` is probably the best way.  You probably want to go in afterwards and filter out blocks that do not align to any of your input genomes (ie that are just ancestor and minigraph) though. `mafFilter` may help you there.

**Comment by BlackSlipper** [comment]
Thank you! I appreciate your help
