### ISSUE TITLE
using --defaultCores 2 breaks clip_vg

### ISSUE THREAD

**Issue by alpapan** [ComparativeGenomicsToolkit/cactus#1539]
when `--defaultCores 2` is provided (or any other value), cactus provides this as a float to the command line, breaking the clip_vg routine:

note 2.0 in command below

```bash
 Running the command: "bash -c set -eo pipefail && clip-vg /tmp/toilwf-52422cb9caa058f3b34ad91805193cca/9551/job/tmpx3nnly5z/1.vg.gfaffixed -f -e v1 -d _MINIGRAPH_ -L -c | vg mod -X 1024 - | vg paths -x - -n -Q v1 -t 2.0 | vg clip -d 1 - -P v1 | vg ids -s -"

exited 1: stderr=error: could not parse i from argument "2.0"

```

**Comment by glennhickey** [comment]
Good catch.  This will be fixed in the next release by way of #1544, until then the only work around is to not use the `--defaultCores` option.  I don't think there's a good use case for `--defaultCores` in cactus anyway -- you will normally be better off using the `--consCores`, `--mapCores`, etc options to finetune the cpu utilization of various stages individually.
