### ISSUE TITLE
Restarting cactus locally on a different node configuration

### ISSUE THREAD

**Issue by evolgen** [ComparativeGenomicsToolkit/cactus#259]
Dear developers,

I am executing cactus locally on a dataset with five high quality genomes and 50 fragmented genomes. Since I have had allocated memory problems the process was killed on a 360Gb machine. 
I restarted the process on a 500Gb machine locally, it has been running without any errors for a few weeks now. The only parameter I specified for for fraction of memory allocated.
`cactus run1 runall.hal --binariesMode local --workDir ./tmp --cleanWorkDir onSuccess --disableCaching --scale 0.96`

Since this process was initially started on lower memory machine (350Gb), the process is not utilizing the newly allocated resources to the fullest (max memory usage is only ~350Gb of 500Gb). The config pickle seems to be a binary file - is there any way to change the allotted memory for a currently running process to use the resources efficiently?

Thank you for your time.

Rohit

**Comment by evolgen** [comment]
@diekhans @glennhickey apologies if this is a trivial question - any input from your side is highly appreciated.

**Comment by diekhans** [comment]
@DailyDreaming @adamnovak I think this has to do with Toil.  Can you advise?

**Comment by adamnovak** [comment]
Can you try setting `--maxMemory 500G` on the command line for the restarted workflow? If you had a `--maxMemory` in the initial run, it does look like it will be preserved when Toil merges the new config and the saved config for the restart: https://github.com/DataBiosphere/toil/blob/b509e8ddc8f94d321e5b1e3af9331d3b377a0d72/src/toil/common.py#L760-L764

But I think if you specify a new value for the option it will override the saved one.

**Comment by evolgen** [comment]
Thank you!!! I restarted the run with more  memory `--maxMemory 500G --defaultMemory 12G --restart`

Currently cactus is trying to restart failed jobs, I will keep you updated once the process resumes.

**Comment by evolgen** [comment]
The job still uses just 350Gb out of the 500Gb available - initial jobs used more RAM but subsequent  RunBlast jobs default  to `cores: 1, disk: 200.0 M, and memory: 200.0 M`

**Comment by adamnovak** [comment]
Changing maxMemory won't affect how big the individual jobs are, just
how many of them will fit at once. If there's a single job that needs
350Gb, it will reserve 350Gb no matter how big your machine is (and
fail if it is too small). If there's a series of 350Gb jobs, they'll
run one at a time on a 500Gb machine.

Those little RunBlast jobs may be  internal Toil promise-resolving or
bookkeeping jobs or something, at that size. If they were created
before you set  --defaultMemory 12G, and Cactus makes them default
size, they won;t automatically get bigger *unless they run and fail
and have their memory bumped to the default). Or they could explicitly
be tiny; maybe they don't actually run Blast themselves but organize
several subjobs that run Blast?

Are any jobs actually failing for you due to insufficient memory
reserved for the job?

**Comment by evolgen** [comment]
Thank you for the detailed info Adam.The jobs are not failing and it has run without problems on the larger node. The process has been running for almost 7 weeks now, is there any way to estimate the endtime or the progress of the current alignment?

**Comment by adamnovak** [comment]
I'm not sure. @glennhickey? Do you know about guessing when Cactus will be done?
