### ISSUE TITLE
"--root mr" means what?

### ISSUE THREAD

**Issue by krabapple** [ComparativeGenomicsToolkit/cactus#267]
Probably a dumb question but in the test example command line, what does 'mr' mean ? 

 I get that --root specifies "Name of ancestral node (which must appear in NEWICK tree in <seqfile>) to use as a root for the alignment."

But in examples/evolverMammals.txt there is no 'mr'.

**Comment by glennhickey** [comment]
It's in the NEWICK tree on the first line.

**Comment by krabapple** [comment]
OK, I was right, dumb question!  But here's another: what does 'mr' stand for?  
((simHuman_chr6:0.144018,(simMouse_chr6:0.084509,simRat_chr6:0.091589)mr:0.271974):0.020593,(simCow_chr6:0.18908,simDog_chr6:0.16303):0.032898);


My own newick tree has 'inode' and 'root'  notations, are these something I need to change for CACTUS?:

((((T_thorsborneae:0.177553,(TVAG:0.049656,T_stableri_putative:0.0361179)inode5:0.155932)inode4:0.0390222,((T_tenax:0.0320812,T_gallinae_TTEN:0.0128406)inode7:0.00858575,T_gallinae:0.0143244)inode6:0.145374)inode3:0.221559,T_foetus_C1_Feline:0.63425)inode2:0,P_hominis:0.450506)root;

**Comment by glennhickey** [comment]
the names in the tree can be whatever you want, so long as they are unique and don't have any crazy special characters.  

on the example tree, we use "mr" to specify the ancestor of "simMouse_chr6" and "simRat_chr6" because mouse starts with "m" and rat starts with "r", but it could have been any other name.
