### ISSUE TITLE
Running (progressive) cactus via Docker

### ISSUE THREAD

**Issue by alancleary** [ComparativeGenomicsToolkit/cactus#37]
Hi there. I'm new to cactus and have been trying to get it up and running via the Docker image on quay.io:
    
```    
docker pull quay.io/comparative-genomics-toolkit/cactus    
```    
    
Unfortunately, the program does not progress beyond parsing the `seqFile`. Specifically, when I run cactus as follows:
    
```    
docker run -v /cactus:/cactus:Z quay.io/comparative-genomics-toolkit/cactus \  
    /cactus/examples/evolverMammals.txt \    
    /cactus/alignment.hal \    
    --maxCpus 4    
```    
    
where `/cactus/examples/evolverMammals.txt` is the example from the repository, I get the error:
    
```    
/cactus/examples/evolverMammals.txt: 1: /cactus/examples/evolverMammals.txt: Syntax error: word unexpected (expecting ")")
```    
    
So for whatever reason it's failing to parse the Newick tree. If I delete the line containing the Newick tree, then I get the error:
    
```    
/cactus/examples/evolverMammals.txt: 1: /cactus/examples/evolverMammals.txt: simCow_chr6: not found
/cactus/examples/evolverMammals.txt: 2: /cactus/examples/evolverMammals.txt: simDog_chr6: not found
/cactus/examples/evolverMammals.txt: 3: /cactus/examples/evolverMammals.txt: simHuman_chr6: not found
/cactus/examples/evolverMammals.txt: 4: /cactus/examples/evolverMammals.txt: simMouse_chr6: not found
/cactus/examples/evolverMammals.txt: 5: /cactus/examples/evolverMammals.txt: simRat_chr6: not found
```    
    
I get the same errors if I try to load my own `seqFile` where the sequence paths are in a subdirectory of `/cactus`.
    
I presume I'm doing something wrong, but I haven't been able to find any documentation on running progressive cactus via the Docker image. Is my `docker run ...` command even running progressive cactus? Any insight would be greatly appreciated!
    
The host OS is Arch Linux with kernel version 4.18.1.

**Comment by joelarmstrong** [comment]
Hi Alan,

Sorry that you are running into trouble. That docker image can't easily be used in that way, sadly--it's meant only to distribute our binary non-Python dependencies (because they can be a colossal pain to compile).

The way it's meant to be run is to install the python bits of Cactus in a virtual environment (e.g. `pip install --upgrade .; pip install toil`, but see the README for details), then run Cactus from there. That Python pipeline will then create a new Singularity/Docker container any time it needs to run one of our C/C++ binaries. (If that sounds a bit strange and convoluted, well, it totally is--but virtually 100% of our use cases require running on a large cluster of some sort, coordinated by the Python bits, and the Docker isolation would often royally mess up the interaction between the Python coordinator and the batch system.)

That said, nothing would prevent creating a Docker container that contains the Python code as well, which would basically just involve following the steps from the README within the Dockerfile. If you really do need to run everything within a single Docker container, I'd be happy to help you with creating that type of image.

**Comment by alancleary** [comment]
Thanks, Joel. That really cleared things up; I was able to run the example to completion.

When the README mentioned Docker, I (falsely) assumed the image contained the virtual environment. Reading it again, it makes so much more sense now! Anyways, all's well that ends well; I still didn't have to build the binaries, which is what I was really trying to accomplish.
