### ISSUE TITLE
Error "TypeError: 'InEdgeDataView' object does not support indexing"

### ISSUE THREAD

**Issue by jerricamae** [ComparativeGenomicsToolkit/cactus#38]
I'm trying to run the evolverMammals.txt cactus example on the interactive node of my cluster. The virtual environment loads correctly, and docker isn't installed so I've been using "--binariesMode local". 

Whenever I run the cactus command with these settings, I get the error "TypeError: 'InEdgeDataView' object does not support indexing". The most recent traceback is to: 

../anaconda2/envs/cactus/lib/python2.7/site-packages/sonLib/nxtree.py", line 71, in getParent
    return edges[0][0]

 I am not well versed in python and was wondering if you had any guidance on how to proceed.

**Comment by joelarmstrong** [comment]
Hi,

I suspect you have a version of the python library networkx that is 2.0 or higher. Those versions changed some aspects of the library that make it incompatible with our code. If you run `pip install networkx==1.11` it should (hopefully) install the version we need. Or if that doesn't work because of permission issues on your cluster, installing cactus inside a virtualenv will help.
