### ISSUE TITLE
Running time estimated from input  format (multiple line /single line)

### ISSUE THREAD

**Issue by Chenglin20170390** [ComparativeGenomicsToolkit/cactus#406]
Hi,  I want to use Cactus more efficiently, So, I have few questions, wish you can help me.
(1) I wandering whether the input fasta format ( multiple lines or one line) will affect running time?   
(2), How do I know the approximate time based on my input data(46 genomes, each 1500Mb, 88CPU), do there has log information to show running progress, and how many jobs need to do. Since  I saw my cactus progress go to 100% again and again.

**Comment by glennhickey** [comment]
The progress bar isn't too useful.  If you run with `--realTimeLogging` you can, say, count the calls to `cactus_setup` in your log.  There will be one for each internal node in your tree, so that should give you a sense.  Another way, which I recommend, is to [break the run into several commands](https://github.com/ComparativeGenomicsToolkit/cactus#running-step-by-step) which would make it easier to track progress.  For 46 1500Mb genomes, I'd guess around 3-4 weeks on 88CPUs but could be way off.

**Comment by Chenglin20170390** [comment]
Ok, many thanks for your kind reply, it's very helpful for us.
