### ISSUE TITLE
Enforce realign is off when running with GPU

### ISSUE THREAD

**Issue by glennhickey** [ComparativeGenomicsToolkit/cactus#465]
Cactus must not be run with `<caf realign="1">` and `<caf gpuLastz="1">`.  This is mentioned [in the REAMDE](https://github.com/ComparativeGenomicsToolkit/cactus#gpu-acceleration) and [applied when releasing GPU docker images](https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/build-tools/makeGpuDockerRelease#L29), but as @thiagogenez noted, something stricter would be useful.  

Either an automatic toggle to `realign="0"` in gpu mode with a warning, or an error forcing the user to change it would suffice I think (former probably best).

**Comment by thiagogenez** [comment]
Thanks, @glennhickey, for that. I agree.  Cactus should stop and outputs an error if both toggles are enabled. I can do a PR for that. 

Anyway, because I was running Cactus with both toggles enabled, I have some measurements that can be useful. The chains of job within `RunSelfBlast ` and `RunBlast` were approximately spending 25% of its runtime on the `run_segalign` while the remaining 75 % were "wasting" on the `cPecanRealign`.
