### ISSUE TITLE
Strange error using Docker image 

### ISSUE THREAD

**Issue by ndtvchris** [ComparativeGenomicsToolkit/cactus#663]
Hello,

I'm attempting to use Cactus via the Docker image. When I try to run Cactus via the command on GitHub, it gives me an error that the output file argument is not recognized. Attached is a picture of the error; the scribbled out part is just me being paranoid and covering my name, but it's the path to the seqFile.
<img width="1067" alt="Screen Shot 2022-02-14 at 11 48 33 AM" src="https://user-images.githubusercontent.com/96163621/153936518-87e2b66c-e8a1-4e59-bf2e-2e1e657e0331.png">

**Comment by glennhickey** [comment]
Cactus expects three arguments:
 `jobstore seqFile outputHal` 
You are supplying four arguments:
 `jobStore XXXXXproject files/sequfile_chris.txt output.hal`  
The extra argument is invalid, which is why it's complaining its unrecognized.  

Note that on the command lines, arguments are separated by spaces.  If you want to use a space in a path name, you need to [quote or escape it](https://stackoverflow.com/questions/589149/bash-script-to-cd-to-directory-with-spaces-in-pathname)
