### ISSUE TITLE
cactus-prepare no longer creates .xml config file?

### ISSUE THREAD

**Issue by gwct** [ComparativeGenomicsToolkit/cactus#750]
Hello,
When running `cactus-prepare`, version 2.1.1 no longer creates the `config-prepared.xml` file in the specified `--outDir`. I am using the GPU version of cactus through a singularity image created from the docker container. This is the command I'm running:

```bash
singularity exec --nv --cleanenv old/cactus_v2.1.1-gpu.sif cactus-prepare genomes.txt --outDir test/ --jobStore jobstore --gpu
```

This results in only the `genomes.txt` file being created in the `test/` directory. When using version 2.0.5, this same command creates both the `genomes.txt` file and the `config-prepared.xml` file.

My questions are:

1. Is the `config-prepared.xml` file still required for subsequent steps (mask, blast, align) via the `--configFile` option?
2. If so, can I just copy an old `config-prepared.xml` file to my new output directory until this issue is fixed? There doesn't seem to be anything dataset specific in the file...

Thanks!
-Gregg

**Comment by glennhickey** [comment]
Sorry for the late reply.  Yeah, that was by design: instead of creating the config.xml, it just passed in the `--gpu` option.  Unfortunately, that option doesn't always work (there are some other issues).  So you are best to double check that segalign is getting run.  It would not hurt to keep passing in your old config.  

We have fixes for all of this and are preparing to release a major update in the coming days.

**Comment by gwct** [comment]
Ok, thanks. So if I'm understanding correctly I _shouldn't_ need to specify a config file with `--configFile` in the future release because the `--gpu` option will handle it.

**Comment by glennhickey** [comment]
That's right.  It's fixed  somewhere in here: https://github.com/ComparativeGenomicsToolkit/cactus/pull/566 and we're waiting on a few large-scale tests to go through before merging it into master and making a new release.
