### ISSUE TITLE
Effect of soft-masking repeats?

### ISSUE THREAD

**Issue by jasonsydes** [ComparativeGenomicsToolkit/cactus#80]
Hello Cactus community!

On the Cactus Github home page, you state:

_Please ensure your genomes are **soft-masked with RepeatMasker**. We do some basic masking as a preprocessing step to ensure highly repetitive elements are masked when repeat libraries are incomplete, but genomes that aren't **properly masked** can still take tens of times longer to align that those that are masked._

I'm trying to get a general sense of a) what you mean by **properly masked**, b) how much soft masking matters (perhaps in terms of runtime / correctness), and c) which masked assemblies we should use (NCBI, Ensembl, UCSC, etc).

It appears that NCBI does a "simple" RepeatMasker run [1], while Ensembl takes a different approach, employing RepeatMasker and RepeatModeler and filtering out repeats possibly associated with protein coding sequences [2].

[1] https://www.ncbi.nlm.nih.gov/genome/annotation_euk/process/
[2] https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4919035/

Just looking at simple counts, the differences in terms of total nucleotides soft masked between NCBI and Ensembl can be quite large, generally with NCBI masking more than Ensembl. Here's a few examples. Coelacanth in particular is striking.

![Screen Shot 2019-05-16 at 11 55 14 AM](https://user-images.githubusercontent.com/182702/57879972-7f0e6c80-77d2-11e9-8aed-7a144b506056.png)

Should I be scared to use the NCBI assemblies? The Ensembl assemblies? Should we be building custom repeat libraries with RepeatModeler when an Ensembl assembly isn't available?  Or am I overthinking this?

Would over-masking result in many fewer alignments?  Or would the output remain the same despite taking much much longer to complete?

Thank you for your feedback!!

**Comment by joelarmstrong** [comment]
Hi Jason,

Sorry about missing this issue. You're right that "properly masked" is a little vague :). I basically intended to mean masked with RepeatMasker using whatever libraries are available. We usually use UCSC/Ensembl assemblies where possible. The tradeoff is, as you've guessed, one between runtime (and the risk of overalignment between a messy tangle of repeats) and the risk of underalignment caused by masking too many bases. In my experience, using assemblies straight from NCBI is OK, but not great: it can sometimes take much longer than using assemblies straight from Ensembl/UCSC.

Over-masking could affect the output, but it would have to be *way* over-masked to have a real effect. The masking only affects the initial alignment phase which finds the anchors -- as long as we find a nearby anchor in an unmasked region, the alignment between the masked regions is recovered by extension from the anchor.

**Comment by jasonsydes** [comment]
Hi @joelarmstrong, thank you again for your thoughtful answers.  I've read your answer above several times and chewed on it quite a bit, it's been quite useful already.  Thank you again for your help.
