### ISSUE TITLE
8A85017 removed how-to-run-it details from README.md

### ISSUE THREAD

**Issue by rsharris** [ComparativeGenomicsToolkit/cactus#807]
The README has been shortened quite a bit, but some helpful details have been removed. In particular, the Running section (now absent) showed the command line and the format of the seqFile.

My guess is that info has been moved to somewhere else. But I'm unable to locate it.

Along those lines, and this predates that change, I've also been unable to locate a man page equivalent that describes the options. I'm running cactus OK, but it is giving me (presumedly helpful) suggestions of settings I should/could change. But I can't find a description. I tried several variations of "cactus -h" and "cactus -help" but had no luck with that. But I'm sure I found a description sometime in the past, because I am using a few options.

**Comment by rsharris** [comment]
Ignore that second part. "cactus -h" and "cactus -help" do give a list of settings. Not sure what I did yesterday that led me to conclude they didn't.

**Comment by glennhickey** [comment]
I added a level of indirection to the README in order to give the pangenome pipeline a little more visibility.  The former README has moved to the [Progressive Cactus Documentation link](https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/doc/progressive.md) in the [Align Genomes From Different Species Header](https://github.com/ComparativeGenomicsToolkit/cactus#align-genomes-from-different-species).  Is what you're looking for there?

**Comment by rsharris** [comment]
Yep, that's it. I figured it was still somewhere. Thanks!
