### ISSUE TITLE
number of cpus//threads

### ISSUE THREAD

**Issue by EricDeveaud** [ComparativeGenomicsToolkit/cactus#820]
some cactus python scripts `cactus_minigraph.py`,  `cactus_graphmap.py`, `cactus_align.py`, `cactus_progressive.py`,  `configWrapper.py`, `dnabrnnMasking.py`,  `cactus_lastzRepeatMask.py` uses toils `cpu_count()` in order to get the number  cpus//threads.
but `toil.lib.threading.cpu_count()`  is the number of physical cpu in the machine which is not the same as the number of available cpu for the process. 
For example, you can run in a taskset context or a batch scheduler like slurm.

see:

```
$ nproc
64
$ taskset -c 1 nproc 
1
$ taskset -c 1 python3 -c "from toil.lib.threading import cpu_count; print(cpu_count())"
64
```
this is a common cause of oversubscription we encouter on our slurm cluster. 
see:

```
maestro-submit:~ > srun  -c 4 python3 -c "from toil.lib.threading import cpu_count; import os; print(cpu_count(), len(os.sched_getaffinity(0)))"
96 4
```

I would suggest to use `len(os.sched_getaffinity(0))` instead of `toil.lib.threading..cpu_count()`
```
$ python3 -c "import os; print(len(os.sched_getaffinity(0)))"
64
$ taskset -c 4 python3 -c "import os; print(len(os.sched_getaffinity(0)))"
4
```

regards

Eric

**Comment by glennhickey** [comment]
Thanks for your suggestion.  This sounds reasonable.  
@adamnovak what do you think?  Should this be what Toil uses for cpu_count too?

**Comment by adamnovak** [comment]
Toil's `cpu_count()` is meant for cases where Toil is scheduling cores on the machine. It respects containerization but not (currently) CPU core pinning.

Toil *jobs* shouldn't try and use it to find out how many cores they are supposed to use, since it always just returns how many cores are on the machine, and a machine can be running multiple jobs. In the Toil Python API, jobs can look at their own `Job` objects to see how many CPUs they have actually been scheduled with. Something like:

```
def my_job_function(job, arg1, arg2):
    subprocess.check_call(['command', '--threads', str(job.cores), arg1, args])

def parent_job_function(job):
    job.addChildJobFn(my_job_function, 'a', 'b', cores=8)
```

The Toil single-machine batch system doesn't touch the (I believe Linux-specific) CPU affinity API, so user code running under the single-machine batch system can't get how many cores it is supposed to be using from `nproc` or `sched_getaffinity` or `toil.lib.threading.cpu_count`. It either has to use the Toil Python API, or it has to use whatever equivalent mechanism CWL or WDL has for subbing in what the CPU requirement was, or it has to check some kind of workflow variable that the workflow author also uses to control the actual requirement.
