### ISSUE TITLE
Cactus 2.3.0 - vg stops with segfault

### ISSUE THREAD

**Issue by leleory** [ComparativeGenomicsToolkit/cactus#850]
Hi all,

In Cactus release 2.3.0, installed from the pre-compiled cactus-bin-v2.3.0.tar.gz, vg returns with segfault.
`~//src/cactus-bin-v2.3.0/bin/vg 
Segmentation fault (core dumped)`
Can you please add a working copy of vg to the tarball or tell me what version of vg would be compatible with this release?

Thanks,
Lel

**Comment by glennhickey** [comment]
Hi.  Thanks for pointing this out.  Something happened during the build to corrupt this binary, apparently.  For a quick patch, replace it with a vg obtained like [this](https://github.com/ComparativeGenomicsToolkit/cactus/blob/v2.3.0/build-tools/downloadPangenomeTools#L283-L284).

I'll update the release shortly.

**Comment by glennhickey** [comment]
What seems to have happened:  I built the vg binary at http://public.gi.ucsc.edu/~hickey/vg-patch/vg.04a8bda9fdbb6f6af66d7aa9ab457d57d1b98e72 on Ubuntu 22.04.  But ran the Cactus build on Ubuntu 18.04.  The build downloads the binary on `strip -d` and everything else in cactus/bin to make them smaller. 

Running `strip -d` (on Ubuntu 18.04) on this binary (built on 22.04) gives a warning
```
strip: warning: vg: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0008002` 
```
but otherwise runs fine and exits 0.  The binary is left corrupted and unusable, though. 

So today I learned that `strip -d` can be dangerous and silently corrupt the input.  Anyway, the [release is now fixed](https://github.com/ComparativeGenomicsToolkit/cactus/releases/tag/v2.3.0).  The docker images seem unaffected.  Thanks again for raising this.
