### ISSUE TITLE
RuntimeError in paf_to_bed: Got an unexpected character paf cigar string: i

### ISSUE THREAD

**Issue by amizeranschi** [ComparativeGenomicsToolkit/cactus#867]
I'm getting an error message `Got an unexpected character paf cigar string: i` at the `paf_to_bed` stage. Any help for solving this would be much appreciated.

I am aligning 7 plant genomes (each around 800 Mb ), 2 of which are chromosome-level, while the rest are scaffold-level. I have previously aligned 4 of the scaffold-level genomes without any problem. This is the command I'm running:

```
docker run -v $(pwd)/data:/data --rm -it quay.io/comparative-genomics-toolkit/cactus:v2.3.0 cactus ./jobStore genomes.txt genomes.hal
```

Full list of error messages is attached below.

[error.txt](https://github.com/ComparativeGenomicsToolkit/cactus/files/10269827/error.txt)

**Comment by glennhickey** [comment]
Sorry, I'm not sure what's happening with this one.  Something is corrupting that file, clearly, but I'm not sure what.  Are you on a normal file system?

**Comment by amizeranschi** [comment]
Yes, I am running things on an XFS file system. Haven't run into any issues with it so far. Any ideas about how to even approach debugging something like this?

**Comment by glennhickey** [comment]
Not too sure, I'm afraid.  Cactus works best when repeats are softmasked beforehand.  If the various paf commands run out of memory or otherwise act up, that's usually a sign that unmasked repeats have caused millions of pairwise alignments to be found in the initial all-vs-all alignment stage, which subsequent steps struggle to handle.  I appreciate that this issue is probably even worse in plants.   We are working on making the automated masking a little more efficient and robust, but that won't be released for a while yet.  Perhaps your chromosome-level assemblies contain unmasked repeats that the scaffolds don't? 

To debug this specific error, you can run with `--disableCaching --cleanWorkDir never` to keep around all temporary files.  You can then inspect the input file it's claiming it is corrupt and maybe deduce something.

**Comment by amizeranschi** [comment]
It looks like the 4 scaffold-level assemblies that I've successfully aligned before aren't softmasked, and neither is one of the chromosome-level assemblies that I've recently added. I will try masking the repeats in all the assemblies and see if that gets things going.

**Comment by amizeranschi** [comment]
Can confirm that softmasking repeats with RepeatModeller + RepeatMasker got things working well. Thanks a lot for the suggestion @glennhickey.

On an unrelated note: how well is Cactus able to handle phylogenetic trees with multifurcations (star trees)? In some cases these are the current best guess due to lack of knowledge, rather than a specific reason for considering the multifurcation event. Given a tree such as `(species1,species2,species3)anc0;`, how could I figure out which one of `((species1,species2)anc1,species3)anc0;` and `(species1,(species2,species3)anc1)anc0;` is "more correct", if there are genome assemblies available for each species?

The section "Effect of the guide tree" from the Progressive Cactus paper seems to suggest that the effect of the tree on the quality of the alignment is minimized. Does this mean that it shouldn't really matter which one of the two binary trees above I use for the input to Cactus? And does this hold for more ambiguous cases, with multifurcations involving 5+ genomes?

**Comment by amizeranschi** [comment]
Alright, thanks again for your helpful comments.
