### ISSUE TITLE
How do we count our Minigraph-Cactus Pangenome results

### ISSUE THREAD

**Issue by ld9866** [ComparativeGenomicsToolkit/cactus#875]
Hello software developer!
Thank you for developing such good software.
At present, we would like to count some indicators of the pan-genome we have built through Minigraph-Cactus Pangenome results, including Nodes, Edges, Reference nodes, Non-reference nodes, Node length, Length of non-reference nodes, Length of small (< Length of non-reference nodes, length of small (< 50 bp) non-reference nodes, Length of large (> 50 bp) non-reference nodes.
Could you tell us how to count these indicators?
Merry Christmas!

**Comment by glennhickey** [comment]
Nodes and edges and node length can all be counted with `vg stats -lz` .

You can count nodes and bases as a function of how many paths cover them with this tool: https://github.com/ComparativeGenomicsToolkit/hal2vg/releases/download/v1.1.2/count-vg-hap-cov which takes '.vg' input (not gbz/gfa).  If you specify a reference with -r it will also give non-reference counts.  I think this is probably your best bet.  It will give you stats for all reference and non-reference nodes and bases.

I don't know of any tools that give these stats broken down by node size.  Be careful because the sizes aren't directly meaningful (ie a large insertion can be broken up into small nodes due to nested variation). But you can get some basic stats for node size by running `awk` on the GFA using length($3) on S lines.  

As mentioned in your [other issue on this](https://github.com/ComparativeGenomicsToolkit/cactus/issues/849#issuecomment-1344418863), I do agree that there should be better tooling/documentation to answer exactly these questions, probably in `vg`.  Hopefully we can get something into the next vg release.

**Comment by ld9866** [comment]
Thank you for your advice
I will use your suggestions to test
Best wishes!
