### ISSUE TITLE
How to genotype the result file primates-pg.vcf.gz of minigraph_cactus？

### ISSUE THREAD

**Issue by abcyulongwang** [ComparativeGenomicsToolkit/cactus#954]
Dear developer!
I have a dozen high-quality genomes of diploid mammals, and I have obtained a graphical pan-genome through Minigraph-Cactus, which we think is accurate and perfect. Of course, we wanted further analysis, so we used Vg software to build a pan-transcriptome. 
After that , I ran `vg autoindex --workflow mpmap --workflow rpvg --prefix vg_rna --ref-fasta ref.fa --vcf primates-pg.vcf.gz --tx-gff ref.gtf`. it got error like this

The output:
[IndexRegistry]: Checking for phasing in VCF(s).
error:[vg autoindex] Input is not sufficient to create indexes
Inputs
GTF/GFF
Reference FASTA
VCF
are insufficient to create target index Haplotype-Transcript GBWT

I've tried adding the parameter --gfa ref.gfa with similar result:

[IndexRegistry]: Checking for phasing in VCF(s).
[IndexRegistry]: Provided: VCF
[IndexRegistry]: Checking for haplotype lines in GFA.
[IndexRegistry]: Provided: Reference GFA
error:[vg autoindex] Input is not sufficient to create indexes

According to other developers' suggestions, it is possible that our vcf file is not phasing, I observed our vcf result file and found that the results of the GT column are not in the usual 0|0, 0|1 or 1|1 format. Our GT column only has one number. Although this result is correct, it may not conform to the input file format of Vg.

![image](https://user-images.githubusercontent.com/93254434/223723051-6b66a246-ef17-4b10-a48a-cd2d2613c3eb.png)

So I would like to get your suggestion on how to solve this problem, is to re-run Minigraph-Cactus? Or are there other tools that can achieve phase.

Here is the link to the previous question for your reference：
https://github.com/jonassibbesen/rpvg/issues/43

Sincerely hope to get your help！
Best

**Comment by glennhickey** [comment]
To make a phased diploid VCF with minigraph-cactus, you need to use the sample names in the input seqfile as described here: https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/doc/pangenome.md#sample-names where you use ".1" and ".2" suffixes for the first and second haplotype of each sample. So chimp.1 and chimp.2 for chimp, gorilla.1 and gorilla.2 for gorilla etc.

Changing the names requires starting from scratch. If you don't want to rerun everything, you can try to edit the GFA output from `cactus-graphmap-join` to fix this information.  The haplotype number is the 3rd column in the W(alk) lines.  So if you have
```
W  chimp_hap1 0 ...
W  chimp_hap2 0 ...
``` 
You'd change this to
```
W  chimp 1 ...
W  chimp 2 ...
```
etc.

From there you can remake the `gbz` from the `gfa` with `vg gbwt` and then regenerate the vcf with `vg deconstruct` and it will be properly phased.

**Comment by hrazif** [comment]
Hello! I was wondering what the genotype calls mean? Is the following assumption correct? 0 --> 0/0 (unphased diploid), 1 --> 0/1, and 2 --> 1/1?

**Comment by glennhickey** [comment]
No. To get diploid calls, you need to use the naming convention.  Otherwise the calls are haploid.  See the [comment just above yours](https://github.com/ComparativeGenomicsToolkit/cactus/issues/954#issuecomment-1460342694)

**Comment by hrazif** [comment]
Thanks! Yes, I saw the comment above, but I am still not sure I understand the VCF format. Is there an easy way to get a VCF with diploid calls (unphased is ok) without having to rerun the whole pipeline? I would appreciate if you give me actual working code (simplified is ok) rather than saying things like run 'vg deconstruct', etc.

**Comment by hrazif** [comment]
Glenn, I was wondering if you have seen my previous comment. I have followed the naming convention, which seems to state that for diploid samples, we should not add .1 or .2. Is that correct? 

I checked my samples file and there is none with .1 or .2 extensions. I am getting values like 1,2,3, etc. in the VCF file generated by minigraph, but I am not sure how to interpret them (convert them to the universal unphased genotype format 0/0, 0/1, 1/1). I would appreciate your help.

**Comment by glennhickey** [comment]
Maybe you are being confused by multiallelic sites...

1. `GT="4"` means haploid sample has 4th alt allele at this site. 
2. `GT="1|4" means phased diploid sample. haplotype one as 1st alt allele, haplotype 2 has 4th. 
3. `GT="0|.|1|0" means phased quadruploid sample. haplotype one and four have reference allele, two is missing data and 3 has first alt allele. 

By default, your VCF will be haploid (first example above), but you can use the naming convetions `.1 etc` to set an arbitrary ploidy. 

If you want only bi-allelic sites (no numbers `> 1` in your `GT`'s), then you can use `bcftools norm` to split up your sites.  

Since this seems more like a misunderstanding of the VCF format itself rather than MC's output, I'm closing the issue for now.

**Comment by hrazif** [comment]
Thanks Glenn for the clarification! I appreciate it. 

Just to clarify, I have been working with VCF files for almost a decade, so the issue definitely is not "a misunderstanding of the VCF format itself" but it is about the way the genotypes are reported in the VCF output from minigraph-cactus. I would appreciate it if you included the clarification you provided about in the main documentation.
