### ISSUE TITLE
RuntimeError: Failed to parse newick tree

### ISSUE THREAD

**Issue by nt365** [ComparativeGenomicsToolkit/cactus#98]
I keep receiving the error found in the "slurm.hal0082.131857976.err.txt" file. My newick tree is in the "drosophila.txt" file. I am unsure of what is incorrect about the tree.

Any feedback here would be appreciated.

[drosophila.txt](https://github.com/ComparativeGenomicsToolkit/cactus/files/3672375/drosophila.txt)
[slurm.hal0082.131857976.err.txt](https://github.com/ComparativeGenomicsToolkit/cactus/files/3672377/slurm.hal0082.131857976.err.txt)

**Comment by joelarmstrong** [comment]
Hi,

I think the newick parser may be getting confused with the names of the internal nodes (since they are numeric it may be trying to parse them as branch lengths).

You should also remove the non-branching nodes (those with only one child). Those nodes will make the alignment take much longer without adding value

**Comment by joelarmstrong** [comment]
Oops, sorry for closing issue, hit the wrong button.

**Comment by nt365** [comment]
Thank you Joel, 

Turns out that the parentheses were unmatched, but I will keep this in mind for any future troubleshooting.
